"""add deep content to lesson

Revision ID: 7b472a203494
Revises: 81b8b8b6bdc7
Create Date: 2026-06-26 18:26:28.853946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b472a203494'
down_revision = '81b8b8b6bdc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('real_world_example', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('code_example', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hands_on_exercise', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mini_project', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('learning_objectives', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lesson_prerequisites', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('best_practices', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('common_mistakes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interview_questions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quizzes_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('quizzes_data')
        batch_op.drop_column('interview_questions')
        batch_op.drop_column('common_mistakes')
        batch_op.drop_column('best_practices')
        batch_op.drop_column('lesson_prerequisites')
        batch_op.drop_column('learning_objectives')
        batch_op.drop_column('mini_project')
        batch_op.drop_column('hands_on_exercise')
        batch_op.drop_column('code_example')
        batch_op.drop_column('real_world_example')
        batch_op.drop_column('explanation')
        batch_op.drop_column('content_generated')

    # ### end Alembic commands ###
