"""add deep content to lesson

Revision ID: 7b472a203494
Revises: 81b8b8b6bdc7
Create Date: 2026-06-26 18:26:28.853946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b472a203494'
down_revision = '81b8b8b6bdc7'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    
    if not inspector.has_table('lessons'):
        return
        
    cols = [c['name'] for c in inspector.get_columns('lessons')]

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        if 'content_generated' not in cols:
            batch_op.add_column(sa.Column('content_generated', sa.Boolean(), nullable=True))
        if 'explanation' not in cols:
            batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))
        if 'real_world_example' not in cols:
            batch_op.add_column(sa.Column('real_world_example', sa.Text(), nullable=True))
        if 'code_example' not in cols:
            batch_op.add_column(sa.Column('code_example', sa.Text(), nullable=True))
        if 'hands_on_exercise' not in cols:
            batch_op.add_column(sa.Column('hands_on_exercise', sa.Text(), nullable=True))
        if 'mini_project' not in cols:
            batch_op.add_column(sa.Column('mini_project', sa.Text(), nullable=True))
        if 'learning_objectives' not in cols:
            batch_op.add_column(sa.Column('learning_objectives', sa.Text(), nullable=True))
        if 'lesson_prerequisites' not in cols:
            batch_op.add_column(sa.Column('lesson_prerequisites', sa.Text(), nullable=True))
        if 'best_practices' not in cols:
            batch_op.add_column(sa.Column('best_practices', sa.Text(), nullable=True))
        if 'common_mistakes' not in cols:
            batch_op.add_column(sa.Column('common_mistakes', sa.Text(), nullable=True))
        if 'interview_questions' not in cols:
            batch_op.add_column(sa.Column('interview_questions', sa.Text(), nullable=True))
        if 'quizzes_data' not in cols:
            batch_op.add_column(sa.Column('quizzes_data', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('quizzes_data')
        batch_op.drop_column('interview_questions')
        batch_op.drop_column('common_mistakes')
        batch_op.drop_column('best_practices')
        batch_op.drop_column('lesson_prerequisites')
        batch_op.drop_column('learning_objectives')
        batch_op.drop_column('mini_project')
        batch_op.drop_column('hands_on_exercise')
        batch_op.drop_column('code_example')
        batch_op.drop_column('real_world_example')
        batch_op.drop_column('explanation')
        batch_op.drop_column('content_generated')

    # ### end Alembic commands ###
