"""add prerequisites to course

Revision ID: 81b8b8b6bdc7
Revises: ecbac70cd03b
Create Date: 2026-06-26 18:23:53.191459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b8b8b6bdc7'
down_revision = 'ecbac70cd03b'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    cols = [c['name'] for c in inspector.get_columns('courses')]
    if 'prerequisites' not in cols:
        with op.batch_alter_table('courses', schema=None) as batch_op:
            batch_op.add_column(sa.Column('prerequisites', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('prerequisites')

    # ### end Alembic commands ###
