"""remove deep content columns batch

Revision ID: f1b34385f0c6
Revises: 7b472a203494
Create Date: 2026-06-26 18:38:45.369875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b34385f0c6'
down_revision = '7b472a203494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('content_generated')
        batch_op.drop_column('explanation')
        batch_op.drop_column('hands_on_exercise')
        batch_op.drop_column('real_world_example')
        batch_op.drop_column('quizzes_data')
        batch_op.drop_column('mini_project')
        batch_op.drop_column('interview_questions')
        batch_op.drop_column('common_mistakes')
        batch_op.drop_column('best_practices')
        batch_op.drop_column('code_example')
        batch_op.drop_column('lesson_prerequisites')
        batch_op.drop_column('learning_objectives')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_objectives', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('lesson_prerequisites', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('code_example', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('best_practices', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('common_mistakes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('interview_questions', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('mini_project', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('quizzes_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('real_world_example', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('hands_on_exercise', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('content_generated', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
